# Add your repo name here
# OR remove it if you're using gh pages as an org
baseurl: "/jekyll-with-js"

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-gzip

exclude:
  - README.md
  - package.json
  - package-lock.json
  - rollup.config.js
  - babel.config.js
